spring.datasource.url=jdbc:mysql://localhost:3306/BeautyStoreDB
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

stripe.secret-key=test_stripe_key