spring.application.name=beautyecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/BeautyStoreDB
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sql/data.sql

#todo: change it to when-authorized later...
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.env.show-values=never
management.endpoint.configprops.show-values=never

logging.level.com.example.beautyecommerce = DEBUG
logging.file.name=logs/application.log
logging.pattern.file={"timestamp":"%d","level":"%p","logger":"%logger","message":"%m"}%n