name: Backend CI

on:
  push:

jobs:
  backend-build:
    runs-on: ubuntu-latest

    services:
        mysql:
            image: mysql:8.0
            env:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: BeautyStoreDB
            ports:
                - 3306:3306
            options: >-
                --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=5


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: mvn test
        working-directory: ./backend
        env:
            SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/BeautyStoreDB
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            LOCAL_STRIPE_SECRET_KEY: test_stripe_key

      - run: mvn package -DskipTests
        working-directory: ./backend
